### ISSUE TITLE
Make environments required in ApiMetadata

### ISSUE THREAD

**Issue by zachkirsch** [fern-api/fern-definition-registry#19]
```yaml
  ApiMetadata:
    properties:
      id: ApiId
      name: string
      description: optional<string>
      logo_s3_url: optional<string>
      git_repo: optional<GitRepo>
      environments: optional<ApiEnvironments> # would rather this is just the map, and it can be empty if need be
```
